version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=LucasPontes=
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:   
      - sqlserver_data:/var/opt/mssql
    restart: always

volumes:
  sqlserver_data:
    driver: local