// <auto-generated />
using System;
using EstacionamentoApp.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstacionamentoApp.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250819001724_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EstacionamentoApp.Domain.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("EmailDono")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("EMAILDONO");

                    b.Property<DateTimeOffset>("HorarioEntrada")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("HORARIOENTRADA");

                    b.Property<DateTimeOffset?>("HorarioSaida")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("HORARIOSAIDA");

                    b.Property<string>("NomeDono")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NOMEDONO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PLACA");

                    b.HasKey("Id");

                    b.HasIndex("EmailDono")
                        .IsUnique();

                    b.ToTable("VEICULOS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
